### PR TITLE
Adapt to Str/List split rename

### PR DESCRIPTION
**Pull request by JRI98**
Fix compile errors after https://github.com/roc-lang/roc/pull/7213
Also update basic-cli to latest in examples.

### CODE REVIEW

**Review by lukewilliamboswell — APPROVED** [review]
Thank you

**Comment by JRI98** [comment]
Is this relevant to the CI failure? https://roc.zulipchat.com/#narrow/channel/463736-bugs/topic/Nightly.20build.20outdated.3F

**Comment by JRI98** [comment]
Should I change [this line](https://github.com/lukewilliamboswell/roc-parser/blob/main/.github/workflows/tests.yaml#L19) to instead point to `https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-TESTING.tar.gz`?

**Comment by lukewilliamboswell** [comment]
I think we can just wait for the new nightly if it's not ready. This isn't blocking you or anything I hope?

**Comment by JRI98** [comment]
Ah no. Just checking if there was anything needed from me 🙂

**Comment by Anton-4** [comment]
> I think we can just wait for the new nightly if it's not ready. This isn't blocking you or anything I hope?

I'd like to have a new release of roc-parser to minimize the time the examples are broken, can we switch this CI workflow to this approach:
```
- id: try_fetching_testing_release
  continue-on-error: true
  run: |
    curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-TESTING.tar.gz

- name: There are no TESTING releases, checking regular releases instead
  if: steps.try_fetching_testing_release.outcome == 'failure'
  run: |
    curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz
```

**Pull request merged**
