### PR TITLE
Enhance the docs for chompUntil and chompWhile

### LINKED ISSUE #2: How to ignore result of a parser?
For example, in Haskell I can do something like:

```haskell
string "Game " >> digits ...
```

I tried using `ignore`, but it doesn't seem to do what I want:

```
ignore (string "Game ") |> \_ -> digits ...
```

What would be the correct way to do it?

### LINKED ISSUE #4: How to match arbitrary string?
Is it possible to match an arbitrary string in a non greedy way? I tried `anyString` however it appears to be greedy. Here's some code.

```
app "label-parser"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br",
        parser: "https://github.com/lukewilliamboswell/roc-parser/releases/download/0.3.0/-e3ebWWmlFPfe9fYrr2z1urfslzygbtQQsl69iH1qzQ.tar.br",
    }
    imports [
        pf.Stdout,
        parser.String.{ parseStr, string, anyString },
        parser.Core.{ apply, const, skip },
    ]
    provides [main] to pf

main =
    Stdout.line "run roc test"

labelParser =
    const \label -> label
    |> apply anyString
    |> skip (string ":")

expect
    result = parseStr labelParser "foo:"
    result == Ok "foo"
```

It results in the error "expected string `:` but found ``." so I assume it's greedy.

I also tried `apply (chompUntil ':')` but I don't think it generates what I want.

Thanks for this awesome library by the way. Let me know if there's a better place to put questions like this.

### PR DESCRIPTION
**Pull request by ryanb**
This adds to the docs for `chompUntil` and `chompWhile` to include examples for capturing the content with `keep`.

Closes #4

### CODE REVIEW

**Review by lukewilliamboswell — APPROVED** [review]
Looks good, thank you 😎

**Comment by lukewilliamboswell** [comment]
Are you able to sign your commits?

**Comment by ryanb** [comment]
> Are you able to sign your commits?

I'm not set up for that, but I'll look into doing this tomorrow. Getting late here. 😄

**Comment by ryanb** [comment]
@lukewilliamboswell commit has been signed

**Pull request merged**
